application: potato-dev01
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"

handlers:
- url: /api/.*
  script: gdn.application
  secure: always
