application: prototype-20140308
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

# other files
- url: /(.*\..*)
  static_files: static/\1
  upload: static/(.*\..*)

# index files
- url: /samples
  static_files: static/index-samples.html
  upload: static/index-samples.html

#- url: /(.+)/
#  static_files: static/\1/index.html
#  upload: static/(.+)/index.html

- url: /api/.*
  script: api.application

- url: /
  static_files: static/index.html
  upload: static/index.html
